# Configuration for probot-stale - https://github.com/probot/stale

# Settings for Pulls:
pulls:
  # Number of days of inactivity before an Pull Request becomes stale
  daysUntilStale: 30

  # Number of days of inactivity before an Pull Request with the stale label is closed.
  daysUntilClose: 10

  # Label to use when marking as stale
  staleLabel: not_ready

  # Exempt Labels
  exemptLabels:
    - WIP
  markComment: >
    This pull request has been automatically marked as stale because it has not had
    recent activity. It will be closed if no further activity occurs. Thank you
    for your contributions.

# Settings for Issues:
issues:
  # Number of days of inactivity before an issue becomes stale
  daysUntilStale: 30

  # Number of days of inactivity before a stale issue is closed
  daysUntilClose: 15

  # Issues with these labels will never be considered stale
  exemptLabels:
    - hold

  # Label to use when marking an issue as stale
  staleLabel: not_ready

  # Comment to post when marking an issue as stale. Set to `false` to disable
  markComment: >
    This issue has been automatically marked as stale because it has not had
    recent activity. It will be closed if no further activity occurs. Thank you
    for your contributions.

  # Comment to post when closing a stale issue. Set to `false` to disable
  closeComment: false
