---
- hosts: localhost
  vars:
    infrared_hosts_dir: "{{ infrared_workspaces_dir }}/active"
    inventory_file_name: "hosts-updated"
  tasks:
    - name: get python interpreter
      shell: |
        ssh stack@{{ undercloud_hostname }} /usr/bin/python --version
      register: python_version
      ignore_errors: true
    - name: python interpreter
      set_fact:
        python_interpreter: "{{ (python_version.stderr_lines|length > 0) | ternary('/usr/libexec/platform-python', '/usr/bin/python') }}"
    - name: add undercloud_host to inventory file
      add_host:
        name: "undercloud"
        groups: "baremetal,undercloud,tester"
        ansible_host: "{{ undercloud_hostname }}"
        ansible_user: "stack"
        ansible_ssh_private_key_file: "{{ ansible_ssh_key }}"
        ansible_python_interpreter: "{{ python_interpreter }}"
    - name: generate inventory file
      template:
        dest: "{{ infrared_hosts_dir }}/{{ inventory_file_name }}"
        src: inventory.j2
    - name: update inventory file symlink
      file:
        dest: "{{ infrared_hosts_file }}"
        state: link
        src: "{{ inventory_file_name }}"
    - name: copy keys
      copy:
        src: "~/.ssh/id_rsa.pub"
        dest: "{{ infrared_hosts_dir }}/id_rsa_undercloud.pub"
