---
- hosts: localhost
  tasks:
      - name: run tripleo-overcloud introspection
        shell: |
            source .venv/bin/activate
            infrared tripleo-overcloud -vvv --version {{ osp_release }} --instackenv-file {{ overcloud_instackenv_path }} --deployment-files {{ nic_configs }} --introspect yes > {{ log_directory }}/overcloud_introspect.log 2&>1
        args:
            chdir: "{{ infrared_dir }}"
        changed_when: false
        ignore_errors: true

- hosts: undercloud
  tasks:
      - name: check and delete introspection failed nodes
        include_tasks: tasks/delete_introspection_failed_nodes.yml
