---
- hosts: localhost
  roles:
    - { role: bootstrap, tags: [ undercloud, introspect, tag, composable, overcloud] }

- import_playbook: scale_compute_vms.yml
  when: scale_compute_vms == true

- hosts: localhost
  gather_facts: yes
  vars:
    chassis_password:  "{{ instackenv_content.nodes[0].pm_password }}"
    osp_rhel_mapping:
      10: 7.7
      13: 7.9
      14: 7.7
      15: 8.0
      16: 8.1
      16.1: 8.2
  roles:
    - { role: install-update-os, tags: [ undercloud, introspect, tag, composable, overcloud], when: virtual_uc != true }
    - { role: set-boot-order, tags: [ undercloud, introspect, tag, composable, overcloud], when: virtual_uc != true }

- import_playbook: virtual_undercloud.yml
  tags:
    - undercloud
    - introspect
    - tag
    - composable
    - overcloud
  when: virtual_uc == true

- hosts: localhost
  gather_facts: yes
  roles:
    - { role: add-undercloud-to-inventory, tags: [ undercloud, introspect, tag, composable, overcloud ] }
    - { role: prepare-nic-configs, tags: [ undercloud, introspect, tag, overcloud ], when: composable_roles == false }
    - { role: composable-preapare-nic-configs, tags: [ undercloud, introspect, tag, composable, overcloud ], when: composable_roles }
    - { role: undercloud, tags: undercloud }
    - { role: introspect, tags: introspect }

- hosts: undercloud
  roles:
    - { role: fault-tolerance-introspection, tags: introspect }

- hosts: localhost
  gather_facts: yes
  roles:
    - { role: tag, tags: tag }
    - { role: composable, tags:  composable, when: composable_roles }

- hosts: undercloud
  gather_facts: yes
  roles:
    - { role: external, tags: [ external, overcloud ] }
    - { role: prep-overcloud, tags: overcloud }

- hosts: localhost
  gather_facts: yes
  roles:
    - { role: overcloud-deploy, tags: overcloud }

- hosts: undercloud
  become: yes
  become_user: stack
  roles:
    - { role: post, tags: [ post, overcloud ] }
    - { role: browbeat, tags: browbeat, when: browbeat is not defined or browbeat == true }

- import_playbook: ocp_on_osp.yml
  tags:
    - shift_stack
  when: shift_stack == true

- hosts: localhost
  roles:
    - { role: cleanup, tags: [ cleanup, never ] }
