- hosts: localhost
  vars:
    container_params: ""
  tasks:
      - name: Setup undercloud.conf
        template:
            src: undercloud.conf.j2
            dest: "{{ undercloud_conf }}"
      - name: Set container params
        set_fact:
          container_params: "--registry-mirror {{ registry_mirror }} --registry-namespace {{ registry_namespace }}"
        when: osp_release > 13
      - name: run tripleo-undercloud
        shell: |
          source {{ infrared_dir }}/.venv/bin/activate
          infrared tripleo-undercloud -vv \
          --version {{ osp_release }} \
          --build {{ osp_puddle }} \
          --images-task rpm \
          --config-file {{ undercloud_conf }} {{ container_params }} &> undercloud_install.log
        args:
            chdir: "{{ infrared_dir }}"
        changed_when: false
