- hosts: localhost
  tasks:
      - name: Setup undercloud.conf
        template:
            src: undercloud.conf.j2
            dest: "{{ undercloud_conf }}"

      - name: run tripleo-undercloud
        shell: |
          source {{ infrared_dir }}/.venv/bin/activate
          infrared tripleo-undercloud -vv \
          --version {{ osp_release }} \
          --build {{ osp_puddle }} \
          --images-task rpm \
          --config-file {{ undercloud_conf }} > {{ log_directory }}/undercloud_install.log 2&>1
        args:
            chdir: "{{ infrared_dir }}"
        changed_when: false
