- hosts: localhost
  vars:
    container_params: ""
  tasks:
      - name: set undercloud local interface
        block:
          - name: get undercloud_local_interface
            shell: |
              for i in /sys/class/net/*
              do
                udevcontent=`udevadm info -p $i --query property`
                if [[ $udevcontent =~ {{ ctlplane_interface }} ]]
                then
                  undercloud_local_interface=`echo $i | cut -d '/' -f 5`
                  break
                fi
              done
              echo $undercloud_local_interface
            register: local_interface
            delegate_to: "{{ undercloud_hostname }}"
            vars:
              ansible_python_interpreter: "{{ python_interpreter }}"
              ansible_user: "stack"
            become: true

          - name: set undercloud_local_interface
            set_fact:
              undercloud_local_interface: "{{ local_interface.stdout }}"
   
          - name: add ip address on undercloud_local_interface
            become: true
            shell:
              ip a a "{{ freeipa_uc_ip }}" brd "{{ freeipa_brd }}" dev "{{ undercloud_local_interface }}"
            changed_when: false
            ignore_errors: yes
            delegate_to: "{{ undercloud_hostname }}"
            when: tls_everywhere == true

        when: virtual_uc != true

      - name: set undercloud_local_interface
        set_fact:
          undercloud_local_interface: "{{ undercloud_local_interface }}"
        when: virtual_uc == true

      - name: Setup undercloud.conf
        template:
            src: undercloud.conf.j2
            dest: "{{ undercloud_conf }}"

      - name: freeipa setting
        copy:
          dest: "{{ infrared_tls_dir }}/defaults/main.yml"
          src: "{{ freeipa_vars }}/freeipa.yml"

      - name: replace value for freeipa_local_interface var
        vars:
          freeipa_interface: "{{ hostvars['freeipa']['freeipa_local_interface'] }}"
        shell: |
          echo {{ freeipa_interface }}
          sed -i 's/freeipa_local_interface/{{ freeipa_interface }}/g' {{ infrared_tls_dir }}/defaults/main.yml

      - name: set_dns for undercloud 
        copy:
          dest: "{{ infrared_tls_dir }}/tasks/set_undercloud_dns.yml"
          src: freeipa/set_undercloud_dns.yml
     
      - name: add task for ipa-client execute
        blockinfile:
          path: /root/infrared/.venv/lib/python2.7/site-packages/infrared/common/roles/tls-everywhere/tasks/prepare_undercloud.yml
          insertbefore:  Prepare novajoin to work
          block: |
            ##ipa-client
              - name: execute ipa-client
                shell: |
                    ipa-client-install --uninstall
                    sudo ipa-client-install --principal=admin --password={{ freeipa_admin_password }} --server={{ freeipa_server_hostname }} --domain={{ freeipa_cloud_domain }} --realm={{ freeipa_realm }} --hostname={{ freeipa_undercloud_hostname }} --unattended --force-join
                changed_when: false
                ignore_errors: true

      - name: Set container params
        set_fact:
          container_params: "--registry-mirror {{ registry_mirror }} --registry-namespace {{ registry_namespace }}"
        when: osp_release > 13

      - name: run tripleo-undercloud
        shell: |
          source {{ infrared_dir }}/.venv/bin/activate
          infrared tripleo-undercloud -vv \
          --version {{ osp_release }} \
          --build {{ osp_puddle }} \
          --images-task rpm \
          --config-file {{ undercloud_conf }} {{ container_params }} > {{ log_directory }}/undercloud_install.log 2>&1
        args:
            chdir: "{{ infrared_dir }}"
        changed_when: false
        when: tls_everywhere != true

      - name: run tripleo-undercloud tls
        shell: |
          source {{ infrared_dir }}/.venv/bin/activate
          infrared tripleo-undercloud -vv \
          --version {{ osp_release }} \
          --build {{ osp_puddle }} \
          --images-task rpm \
          --config-file {{ undercloud_conf }} {{ container_params }} --tls-everywhere true > {{ log_directory }}/undercloud_install.log 2>&1
        args:
            chdir: "{{ infrared_dir }}"
        changed_when: false
        when: tls_everywhere == true

