---
- name: copy jump host key
  shell: |
    echo '{{ ansible_ssh_pass }}' | sshpass ssh-copy-id  -o 'StrictHostKeyChecking no' -f {{ ansible_ssh_user }}@{{ hostname }}
  register: ssh_result
  changed_when: false
  ignore_errors: true

- name: remove key and add again
  shell: |
    ssh-keygen -q -b 2048 -t rsa -N "" -C "creating SSH" -f {{ ansible_ssh_key }}
    echo '{{ ansible_ssh_pass }}' | sshpass ssh-copy-id -i {{ ansible_ssh_key }} -o 'StrictHostKeyChecking no' -f {{ ansible_ssh_user }}@{{ hostname }}
  changed_when: false
  when: ssh_result.stderr_lines|length > 0

