---
# tasks file for set-boot-order
- name: list oc_instackenv_content
  shell: |
    echo "{{ (oc_instackenv_content.nodes[item | int].pm_addr | replace('mgmt-','') | replace('-drac', '')) }}"
  with_sequence: 0-{{ (oc_instackenv_content.nodes|length - 1) }}
  register: host_list

- block:
    - name: set boot order to director
      include_tasks: set_boot_order.yml
  rescue:
    - name: Reset iDrac
      shell: |
        sshpass -p {{ chassis_password }} ssh -o StrictHostKeyChecking=no quads@mgmt-{{ item.stdout }} "racadm racreset soft -f"
      with_items:
        - "{{ host_list.results }}"

    - name: Wait for iDrac to be responsive
      shell: |
        source {{ badfish_venv }}/bin/activate;
        python3 badfish.py -H mgmt-{{ item[1].stdout }}  -u quads -p {{ chassis_password }} -i "{{ ansible_user_dir }}/badfish/config/idrac_interfaces.yml" --check-boot
      args:
        chdir: "{{ ansible_user_dir }}/badfish/src/badfish"
      when: vendors is defined and item[0] == "dell"
      with_together:
        - "{{ vendors }}"
        - "{{ host_list.results }}"
      register: wait_for_idrac
      until: wait_for_idrac is succeeded
      retries: 20
      delay: 30

    - name: try again setting boot order to director
      include_tasks: set_boot_order.yml
  when: lab_name in ['scale', 'alias'] and set_boot_order == true
